[package]
name = "cache_versteck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drand_core = "0.0.7"
tlock = "0.0.2"
bevy = "0.10.1"